modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="fastfooddelight" #mandatory
version="${file.jarVersion}" #mandatory
displayName="https://github.com/akaneoMT/FastFoodDelight" #mandatory
logoFile="logo.png" #optional
logoBlur=false
credits="vectorwing" #optional
authors="Akaneo" #optional
description="A lightweight fast food expansion for Minecraft!"
itemIcon="fastfooddelight:french_fries"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.fastfooddelight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fastfooddelight]] #optional
modId="farmersdelight" #mandatory
mandatory=true #mandatory
versionRange="[1.2.0,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.fastfooddelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
